config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :stories
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  validates_presence_of :title, :content

  # default_scope { where(deleted_at: nil) }
  scope :deleted, -> { where.not(deleted_at: nil) }
  scope :published, -> { where(deleted_at: nil) }
  def destroy
    update(deleted_at: Time.now)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :stories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  private

  def record_not_found
    render file: "#{Rails.root}/public/404.html",
           status: :not_found,
           layout: false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/stories_controller.rb
# rubocop:disable Metrics/MethodLength
class StoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_story, only: %i[edit update destroy]

  def index
    @stories = current_user.stories.published.order(created_at: :asc)
  end

  def show
    @story = current_user.stories.find(params[:id])
  end

  def new
    @story = current_user.stories.new
  end

  def create
    @story = current_user.stories.new(story_params)
    @story.status = 1 if params[:publish]
    if @story.save
      if params[:publish]
        redirect_to stories_path, notice: '新增成功！！'
      else
        redirect_to edit_story_path(@story), notice: '已存成草稿'
      end
    else
      render :new
    end
  end

  def edit; end

  def update
    if @story.update(story_params)
      if params[:publish]
        redirect_to stories_path, notice: '更新成功！！'
      else
        redirect_to edit_story_path(@story), notice: '已存成草稿'
      end
    else
      render :edit
    end
  end

  def destroy
    @story.destroy
    redirect_to stories_path, notice: '文章已刪除！'
  end

  private

  def story_params
    params.require(:story).permit(:title, :content, :status)
  end

  def find_story
    @story = current_user.stories.find(params[:id])
  end
end

# rubocop:enable Metrics/MethodLength

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
# rubocop:disable Metrics/CyclomaticComplexity, Metrics/MethodLength
module StoriesHelper
  def flash_class(notice)
    case notice
    when '新增成功！'
      'is-primary'
    when '更新成功！'
      'is-primary'
    when '文章已刪除！'
      'is-danger'
    when '成功登出了。'
      'is-primary'
    when '或密碼錯誤。'
      'is-danger'
    when '已成功登入。'
      'is-primary'
    when '註冊成功，歡迎！'
      'is-warning'
    else
      'is-info'
    end
  end
end

# rubocop:enable Metrics/CyclomaticComplexity, Metrics/MethodLength

app/helpers/users_helper.rb
# rubocop:disable Metrics/MethodLength
module UsersHelper
  def alert_class(alert)
    case alert
    when '電子信箱或密碼錯誤。'
      'is-danger'
    when '成功登出了。'
      'is-primary'
    when '已成功登入。'
      'is-primary'
    when '註冊成功，歡迎！'
      'is-warning'
    else
      'is-info'
    end
  end
end

# rubocop:enable Metrics/MethodLength

app/views/home/index.html.erb
<h1>HomePage</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MediumDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'true' %>
  </head>
  <body>
    <%= render 'shared/frontend/navbar' %>
    <%= render 'shared/frontend/flash' if flash[:notice].present? || flash[:alert].present? %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/layout/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item" href="https://bulma.io">
      <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28">
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item">
        Home
      </a>

      <a class="navbar-item">
        Documentation
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>

        <div class="navbar-dropdown">
          <a class="navbar-item">
            About
          </a>
          <a class="navbar-item">
            Jobs
          </a>
          <a class="navbar-item">
            Contact
          </a>
          <hr class="navbar-divider">
          <a class="navbar-item">
            Report an issue
          </a>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <a class="button is-primary">
            <strong>Sign up</strong>
          </a>
          <a class="button is-light">
            Log in
          </a>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/frontend/_flash.html.erb
<div class="notification <%= flash[:notice].present?  ? flash_class(flash[:notice]) : alert_class(flash[:alert]) %>">
  <button class="delete"></button>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
</div>

app/views/shared/frontend/_navbar.html.erb
<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
  <div class="navbar-brand is-vcentered">
    <%= link_to 'LOGO', root_path, class: "navbar-item", id: "app-logo"%>
    <a role="button" class="navbar-burger my-auto" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>
  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
    </div>
    <div class="navbar-end">
      <% if user_signed_in? %>
        <div class="navbar-item">
          <div class="buttons">
            <div class="navbar-item has-dropdown is-hoverable has-text-white">
              <a class="navbar-link">
                <%= current_user.email %>
              </a>
              <div class="navbar-dropdown">
                <%= link_to '新增故事', new_story_path, class: "navbar-item" %>
                <%= link_to '管理文章', stories_path, class: "navbar-item" %>
              </a>
              <hr class="navbar-divider">
              <%= link_to '個人資料', edit_user_registration_path, class: "is-info navbar-item" %>
              <%= link_to  '登出', destroy_user_session_path,  class: "navbar-item is-danger", method: :delete, data: {  confirm: "確定要登出嗎?", } %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="navbar-item columns is-2">
        <div class="column">
          <%= link_to '註冊', new_user_registration_path, class: "button is-primary" %>
        </div>
        <div class="column">
          <%= link_to '登入', new_user_session_path , class: "button is-danger" %>
        </div>
      </div>
    <% end %>
  </div>
</div>
</nav>

app/views/stories/_form.html.erb
<%= form_for story do |f| %>
  <div class="feild is-three-fifths is-offset-one-fifth">
    <%= f.label :title, '標題', class: 'label' %>
    <%= f.text_field :title, class: 'input is-medium is-primary autofocus' %>
  </div>
  <div class="field">
    <%= f.label :content, '內容', class: 'label' %>
    <%= f.text_area :content, class: 'textarea is-medium is-primary' %>
  </div>
  <div class="field">
    <%= f.submit '儲存草稿', name: 'save_as_draft', class: 'button is-light is-medium' %>
    <%= f.submit '發布文章', name: 'publish', class: 'button is-primary is-medium' %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<h1 class="title">編輯文章頁面</h1>
<%= render partial: 'stories/form', locals: { story: @story } %>

app/views/stories/index.html.erb
<h1 class="title">故事列表</h1>
<table class="table">
  <%= link_to '新增文章', new_story_path, class: 'button is-primary' %>
  <thead>
    <tr>
      <th><abbr title="Position">ID</abbr></th>
      <th>標題</th>
      <th>狀態</th>
      <th></th>
      <th></th>
      <th><abbr title="Goals for">上傳時間</abbr></th>
      <th><abbr title="Goals against">最後更新時間</abbr></th>
      <th>內文</th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th><abbr title="Position">ID</abbr></th>
      <th>標題</th>
      <th>狀態</th>
      <th></th>
      <th></th>
      <th><abbr title="Goals for">上傳時間</abbr></th>
      <th><abbr title="Goals against">最後更新時間</abbr></th>
      <th>內文</th>
    </tr>
  </tfoot>
  <tbody>
    <% @stories.each do |story| %>
      <tr>
        <th>
          <%= story.id %>
        </th>
        <td>
          <h2 class="subtitle">
            <%= link_to story.title, story_path(story) %>
          </h2>
        </td>
        <td>
          <%= story.status == 0 ? '草稿' : '已發布' %>
        </td>
        <td>
          <%= link_to '編輯', edit_story_path(story), class: 'button is-light  is-small' %>
        </td>
        <td>
          <%= link_to '刪除', story_path(story), method: :delete, class: 'button is-danger is-small', data: { confirm: '確定要刪除嗎?' } %>
        </td>
        <td><%= story.created_at.strftime('%Y/%m/%d') %></td>
        <td><%= time_ago_in_words(story.updated_at) %></td>
        <td>
          <p class="block"><%= story.content %></p>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stories/new.html.erb
<h1 class="title">新增故事</h1>
<%= form_for @story do |f| %>
  <div class="feild">
    <%= f.label :title, '標題', class: 'label' %>
    <%= f.text_field :title, class: 'input is-medium is-primary autofocus' %>
  </div>
  <div class="field">
    <%= f.label :content, '內容', class: 'label' %>
    <%= f.text_area :content, class: 'textarea is-medium is-primary' %>
  </div>
  <div class="field">
    <%= f.submit '儲存草稿', class: 'button is-light is-medium' %>
    <%= f.submit '發布文章', class: 'button is-primary is-medium' %>
  </div>
<% end %>

app/views/stories/show.html.erb
<h1 class="title">
  <%= @story.title %>
</h1>
<p class="block">
  <%= @story.content %>
</p>
<%= link_to '回文章列表', stories_path, class: 'button is-light' %>